### PR TITLE
fix W19 warning in vim > 7.4.2119

### PR DESCRIPTION
**Pull request by kazufukurou**

### CODE REVIEW

**Comment by tyru** [comment]
プルリクエストありがとうございます。
W19 の警告を発生させる手順を教えて頂いてもよろしいでしょうか？

**Comment by tyru** [comment]
Thanks for a pull request.
Could you give me a step to reproduce the problem?

**Comment by kazufukurou** [comment]
1) install vim 7.4.2156
2) install skk.vim
3) open any file in vim and wait for 5 seconds

**Comment by tyru** [comment]
Thanks. I'll try it :)

**Comment by tyru** [comment]
Confirmed the problem on MSYS Vim at 7.4.2295 .

```
:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 31 2016 22:42:10)
適用済パッチ: 1-2295
Compiled by tyru <tyru.exe@gmail.com>
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
+acl             +cmdline_hist    -ebcdic          +gettext         +listcmds        +mouse_sgr       +persistent_undo +smartindent     +textobjects     +wildmenu
+arabic          +cmdline_info    +emacs_tags      -hangul_input    +localmap        -mouse_sysmouse  +postscript      +startuptime     +timers          +windows
+autocmd         +comments        +eval            +iconv           +lua             +mouse_urxvt     +printer         +statusline      +title           +writebackup
-balloon_eval    +conceal         +ex_extra        +insert_expand   +menu            +mouse_xterm     +profile         -sun_workshop    -toolbar         -X11
-browse          +cryptv          +extra_search    +job             +mksession       +multi_byte      -python          +syntax          +user_commands   -xfontset
++builtin_terms  +cscope          +farsi           +jumplist        +modify_fname    +multi_lang      -python3         +tag_binary      +vertsplit       -xim
+byte_offset     +cursorbind      +file_in_path    +keymap          +mouse           -mzscheme        +quickfix        +tag_old_static  +virtualedit     -xpm
+channel         +cursorshape     +find_in_path    +lambda          -mouseshape      +netbeans_intg   +reltime         -tag_any_white   +visual          -xsmp
+cindent         +dialog_con      +float           +langmap         +mouse_dec       +num64           +rightleft       -tcl             +visualextra     -xterm_clipboard
-clientserver    +diff            +folding         +libcall         -mouse_gpm       +packages        -ruby            +termguicolors   +viminfo         -xterm_save
+clipboard       +digraphs        -footer          +linebreak       -mouse_jsbterm   +path_extra      +scrollbind      +terminfo        +vreplace
+cmdline_compl   -dnd             +fork()          +lispindent      +mouse_netterm   -perl            +signs           +termresponse    +wildignore
      システム vimrc: "$VIM/vimrc"
      ユーザー vimrc: "$HOME/.vimrc"
   第2ユーザー vimrc: "~/.vim/vimrc"
       ユーザー exrc: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
       省略時の $VIM: "/home/tyru/vim.head/share/vim"
コンパイル: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
リンク: gcc   -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lncurses  -liconv -lacl -lintl  -L/usr/local/lib -llua
```

**Comment by tyru** [comment]
@kazufukurou Thanks!

**Pull request merged**
